MessageStore.Dashboard/Models/ErrorViewModel.cs
using System;

namespace MessageStore.Dashboard.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MessageStore.Dashboard/Models/Message.cs
using System;

namespace MessageStore.Dashboard.Models
{
    public class Message 
    {
        public int Id { get; set; }

        public string Title { get; set; }

        public string Body { get; set; }

        public DateTime CreatedAt { get; set; }

        public DateTime ModifiedAt { get; set; }
    }
}

MessageStore.Dashboard/Models/MessageDto.cs
namespace MessageStore.Dashboard.Models
{
    public class MessageDto
    {
        public string Title { get; set; }

        public string Body { get; set; }
    }
}

MessageStore.Dashboard/Controllers/CreateController.cs
using System.Diagnostics;
using System.Net;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;
using MessageStore.Dashboard.Models;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace MessageStore.Dashboard.Controllers
{
    public class CreateController : Controller
    {
        private readonly HttpClient _client;

        public CreateController(HttpClient client) 
        {
            _client = client;
        }

        public IActionResult Index(string errorMessage = null, MessageDto message = null)
        {
            if (errorMessage != null)
            {
                ViewBag.ErrorMessage = errorMessage;
                if (message != null)
                {
                    return View(message);
                }
            }

            return View();
        }

        [ActionName("save")]
        public async Task<IActionResult> PostAsync(MessageDto messageToSave)
        {
            string json = JsonConvert.SerializeObject(messageToSave, Formatting.None);
            var httpContent = new StringContent(json, Encoding.UTF8, "application/json");

            HttpResponseMessage response = await _client.PostAsync($"api/messages/", httpContent);

            if (response.IsSuccessStatusCode)
            {
                return RedirectToAction("Index", "Home");
            }

            if (response.StatusCode == HttpStatusCode.BadRequest)
            {
                string message = "Please check your input data. Make sure both fields are not empty and Title cannot equal to Body";
                return RedirectToAction("Index", new {errorMessage = message, message = messageToSave});
            }

            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MessageStore.Dashboard/Controllers/EditController.cs
using System.Diagnostics;
using System.Net;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;
using MessageStore.Dashboard.Models;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace MessageStore.Dashboard.Controllers
{
    public class EditController : Controller
    {
        private readonly HttpClient _client;

        public EditController(HttpClient client) 
        {
            _client = client;
        }

        public async Task<ActionResult> Index(int? messageId, string errorMessage = null, Message messageToFix = null)  
        {  
            if(messageId == null) 
            {
                return NotFound();
            }

            if (errorMessage != null)
            {
                ViewBag.ErrorMessage = errorMessage;
                if (messageToFix != null)
                {
                    return View(messageToFix);
                }
            }

            Message message = null;
            HttpResponseMessage response = await _client.GetAsync($"api/messages/{messageId}");  
  
            if (response.IsSuccessStatusCode)  
            {
                string result = await response.Content.ReadAsStringAsync();  
                message = JsonConvert.DeserializeObject<Message>(result);  
            }

            return View(message);  
        }

        [ActionName("save")]
        public async Task<IActionResult> PutAsync(Message messageToSave)
        {
            string json = JsonConvert.SerializeObject(messageToSave, Formatting.None);
            var httpContent = new StringContent(json, Encoding.UTF8, "application/json");

            HttpResponseMessage response = await _client.PutAsync($"api/messages/{messageToSave.Id}", httpContent);

            if (response.IsSuccessStatusCode)
            {
                return RedirectToAction("Index", "Home");
            }

            if (response.StatusCode == HttpStatusCode.BadRequest)
            {
                string message = "Please check your input data. Make sure both fields are not empty and Title cannot equal to Body.";
                return RedirectToAction("Index", new { errorMessage = message, messageToFix = messageToSave });
            }

            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MessageStore.Dashboard/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MessageStore.Dashboard.Models;
using System.Net.Http;
using System.Net.Http.Headers;
using Newtonsoft.Json;

namespace MessageStore.Dashboard.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

MessageStore.Dashboard/Controllers/PatchController.cs
using System.Diagnostics;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;
using MessageStore.Dashboard.Models;
using Microsoft.AspNetCore.JsonPatch;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace MessageStore.Dashboard.Controllers
{
    public class PatchController : Controller
    {
        private readonly HttpClient _client;

        public PatchController(HttpClient client)
        {
            _client = client;
        }

        public async Task<IActionResult> Index(int? messageId, bool patchTitle)
        {
            if (messageId == null)
            {
                return NotFound();
            }

            Message message = null;
            HttpResponseMessage result = await _client.GetAsync($"api/messages/{messageId}");

            if (result.IsSuccessStatusCode)
            {
                string response = await result.Content.ReadAsStringAsync();
                message = JsonConvert.DeserializeObject<Message>(response);
            }

            ViewBag.PatchTitle = patchTitle;

            return View(message);
        }

        [ActionName("patchtitle")]
        public async Task<IActionResult> PatchTitleAsync(Message message)
        {
            if (message.Title == null)
                return BadRequest();

            var patchDoc = new JsonPatchDocument<MessageDto>();
            patchDoc.Replace(e => e.Title, message.Title);

            string serializedPatch = JsonConvert.SerializeObject(patchDoc, Formatting.None);
            var httpContent = new StringContent(serializedPatch, Encoding.UTF8, "application/json");

            string url = $"api/messages/{message.Id}";
            HttpResponseMessage response = await _client.PatchAsync(url, httpContent);

            if (response.IsSuccessStatusCode)
            {
                return RedirectToAction("Index", "Home");
            }

            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        [ActionName("patchbody")]
        public async Task<IActionResult> PatchBodyAsync(Message message)
        {
            if (message.Body == null)
                return BadRequest();

            var patchDoc = new JsonPatchDocument<MessageDto>();
            patchDoc.Replace(e => e.Body, message.Body);

            var serializedPatch = JsonConvert.SerializeObject(patchDoc);
            var httpContent = new StringContent(serializedPatch, Encoding.UTF8, "application/json");

            string url = $"api/messages/{message.Id}";
            HttpResponseMessage response = await _client.PatchAsync(url, httpContent);

            if (response.IsSuccessStatusCode)
            {
                return RedirectToAction("Index", "Home");
            }

            return View(new ErrorViewModel{ RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MessageStore.Dashboard/Views/Create/Index.cshtml
@model MessageDto
@{
    ViewData["Title"] = "Create Page";
}

@if (ViewBag.ErrorMessage != null)
{
    <div style="margin-top: 15px; color: red">@ViewBag.ErrorMessage</div>
}

<form method="post" asp-controller="Create" asp-action="save">
    <div class="form-group row" style="margin-top:10px;">
        <div class="col-xs-3">
            <label for="title">Title:</label>
            <input asp-for="Title" class="form-control" id="title" maxlength="100">
        </div>
    </div>
    <div class="form-group row">
        <div class="col-xs-4">
            <label for="body">Body:</label>
            <textarea asp-for="Body" class="form-control" id="body" maxlength="500"></textarea>
        </div>
    </div>

    <button type="submit">Save</button>
</form>

MessageStore.Dashboard/Views/Edit/Index.cshtml
@using MessageStore.Dashboard.Controllers;

@model Message;

@{
    ViewData["Title"] = "Edit Page";
}

@if (ViewBag.ErrorMessage != null)
{
    <div style="margin-top: 15px; color: red">@ViewBag.ErrorMessage</div>
}

<form method="post" asp-controller="Edit" asp-action="save">
    <input type="hidden" asp-for="Id" />
    <div class="form-group row" style="margin-top:10px;">
        <div class="col-xs-3">
            <label for="title">Title:</label>
            <input asp-for="Title" class="form-control" id="title" maxlength="100">
        </div>
    </div>
    <div class="form-group row">
        <div class="col-xs-4">
            <label for="body">Body:</label>
            <textarea asp-for="Body" class="form-control" id="body" maxlength="500"></textarea>
        </div>
    </div>
    <button type="submit">Save</button>
</form>

MessageStore.Dashboard/Views/Home/Index.cshtml
@inject MessageStore.Dashboard.Configuration.IApplicationConfiguration appSettings;
@{
    ViewData["Title"] = "Messages Page";
    string apiUrl = appSettings.MessageStoreApiUrl;
}

<div class="row" style="margin-bottom:20px">
    <h2>Messages</h2>
    <div class="col-md-12">
        <a class="btn btn-success" href="/Create">Add message</a>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <table id="messages" class="table table-striped table-bordered dt-responsive nowrap" cellspacing="0">
            <thead>
                <tr>
                    <th>Title</th>
                    <th>Body</th>
                    <th>CreatedAt</th>
                    <th>ModifiedAt</th>
                    <th>Edit</th>
                    <th>Delete</th>
                    <th>Patch Title</th>
                    <th>Patch Body</th>
                </tr>
            </thead>
        </table>
    </div>
</div>

<script>
    var messageTable;
    function DeleteData(CustomerID) {
        if (confirm("Are you sure you want to delete ...?")) {
            Delete(CustomerID);
        }
        else {
            return false;
        }
    }

    function Delete(messageId) {
        var url = "@apiUrl" + "api/messages/" + messageId;
        $.ajax({
            url: url,
            type: 'DELETE',
            success: function (result) {
                messageTable.ajax.reload();
            }
        });
    }

    $(document).ready(function () {
        messageTable = $("#messages").DataTable({
            "processing": false,
            "serverSide": false,
            "filter": false,
            "orderMulti": false,
            "pageLength": 10,

            "ajax": {
                "url": "@apiUrl" + "api/messages",
                "type": "GET",
                "datatype": "json",
                "dataSrc": ''
            },

            "columnDefs":
                [
                    {
                        "targets": [0],
                        "visible": true,
                        "searchable": false,
                        "render": function(data, type, full, meta) {

                            var result = data = typeof data === 'string' && data.length > 10 ? data.substring(0, 10) + '...' : data;
                            return result;
                        }
                    },
                    {
                        "targets": [1],
                        "visible": true,
                        "searchable": false,
                        "render": function(data, type, full, meta) {

                            var result = data = typeof data === 'string' && data.length > 10 ? data.substring(0, 10) + '...' : data;
                            return result;
                        }
                    },
                    {
                        "targets": [2],
                        "visible": true,
                        "render": function (data, type, row) {
                            var date = new Date(data);
                            return date.getDate() + "." + date.getMonth() + "." + date.getFullYear() + " " + date.getHours() + "." + date.getMinutes();
                        }
                    },
                    {
                        "targets": [3],
                        "visible": true,
                        "render": function (data, type, row) {
                            var date = new Date(data);
                            return date.getDate() + "." + date.getMonth() + "." + date.getFullYear() + " " + date.getHours() + "." + date.getMinutes();
                        }
                    },
                    {
                        "targets": [4],
                        "orderable": false,
                    },
                    {
                        "targets": [5],
                        "orderable": false,
                    },
                    {
                        "targets": [6],
                        "orderable": false,
                    },
                    {
                        "targets": [7],
                        "orderable": false,
                    }
                ],

            "columns": [
                { "data": "Title", "name": "Title", "autoWidth": true },
                { "data": "Body", "name": "Body", "autoWidth": true },
                { "data": "CreatedAt", "name": "CreatedAt", "autoWidth": true },
                { "data": "ModifiedAt", "name": "ModifiedAt", "autoWidth": true },
                {
                    "render": function (data, type, full, meta) { return '<a class="btn btn-primary" href="/Edit?messageId=' + full.Id + '">Edit</a>'; }
                },
                {
                    render: function (data, type, full, meta) { return "<a href='#' class='btn btn-danger' onclick=DeleteData('" + full.Id + "'); >Delete</a>"; }
                },
                {
                    "render": function (data, type, full, meta) { return '<a class="btn btn-warning" href="/Patch?messageId=' + full.Id + '&patchTitle=true">Patch title</a>'; }
                },
                {
                    "render": function (data, type, full, meta) { return '<a class="btn btn-info" href="/Patch?messageId=' + full.Id + '&patchTitle=false">Patch Body</a>'; }
                }
            ]
        });
    });
</script>

MessageStore.Dashboard/Views/Patch/Index.cshtml
@model Message;

@{
    ViewData["Title"] = "Patch Page";
}

@if (ViewBag.PatchTitle)
{
    <form asp-controller="Patch" asp-action="patchtitle" method="post">
        <div class="form-group row" style="margin-top:10px;">
            <div class="col-xs-3">
                <label for="title">Title:</label>
                <input type="hidden" asp-for="Id" />
                <input asp-for="Title" id="messageTitle" class="form-control" maxlength="500">
            </div>
        </div>
        <button class="btn btn-primary" id="submitButton" type="submit">Save</button>
    </form>
}
else
{
    <form asp-controller="Patch" asp-action="patchbody" method="post">
        <div class="form-group row">
            <div class="col-xs-4">
                <label for="body">Body:</label>
                <input type="hidden" asp-for="Id" />
                <textarea asp-for="Body" id="messageBody" class="form-control" maxlength="500"></textarea>
            </div>
        </div>
        <button class="btn btn-primary" type="submit" id="submitButton">Save</button>
    </form>
}

<script type="text/javascript">
    var patchTitle = @ViewBag.PatchTitle.ToString().ToLower();
    if (patchTitle) {
        $("#messageTitle").keyup(function () {
            var emptyInput = this.value == "" ? true : false;
            $("#submitButton").prop("disabled", emptyInput);
        });
    } else {
        $("#messageBody").keyup(function() {
            var emptyInput = this.value == "" ? true : false;
            $("#submitButton").prop("disabled", emptyInput);
        });
    }

</script>

MessageStore.Dashboard/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MessageStore</title>

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs/dt-1.10.18/b-1.5.2/r-2.2.2/sl-1.2.6/datatables.min.css" />
    <script type="text/javascript" src="https://cdn.datatables.net/v/bs/dt-1.10.18/b-1.5.2/r-2.2.2/sl-1.2.6/datatables.min.js"></script>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Dashboard</a>
            </div>
        </div>
    </nav>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - MessageStore</p>
        </footer>
    </div>

    @RenderSection("Scripts", required: false)
</body>
</html>